{{- if .Values.usingGCPController }}
apiVersion: gcp.kiwigrid.com/v1beta1
kind: GcpServiceAccount
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gcloud-sqlproxy.fullname" . }}
spec:
  serviceAccountIdentifier: {{ include "gcloud-sqlproxy.serviceAccountName" . }}
  serviceAccountDescription: Service account for accessing a managed sql instance
  secretName: {{ include "gcloud-sqlproxy.secretName" . }}
  bindings:
  {{ range .Values.cloudsql.instances -}}
  - resource: "//cloudresourcemanager.googleapis.com/projects/{{ .project }}"
    roles:
    - roles/cloudsql.client
  {{ end }}
{{ end }}