{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ include "gcloud-sqlproxy.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    # Allow inbound connections
    - ports:
      {{- range .Values.cloudsql.instances }}
      - port: {{ .port }}
      {{- end }}
      from:
{{ toYaml .Values.networkPolicy.ingress.from | indent 10 }}
{{- end }}
