{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gcloud-sqlproxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "gcloud-sqlproxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
