{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gcloud-sqlproxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gcloud-sqlproxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
