{{- if .Values.useStatefulset }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}-headless
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range .Values.cloudsql.instances }}
  {{- $instanceShortName := include "gcloud-sqlproxy.instanceShortName" . }}
  - name: {{ $instanceShortName }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ $instanceShortName }}
  {{- end }}
  selector:
    {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
{{- end }}
