{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  annotations:
  {{- if .Values.service.internalLB  }}
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  {{- range  $key, $value := .Values.service.annotations  }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range .Values.cloudsql.instances }}
  {{- $instanceShortName := include "gcloud-sqlproxy.instanceShortName" . }}
  - name: {{ $instanceShortName }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ $instanceShortName }}
  {{- end }}
  selector:
    {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
{{- end }}
