apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  {{- if .Values.service.internalLB  }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.cloudsql.instances }}
  - name: {{ .instance }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}