apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "contour.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "contour.name" . }}
    chart: {{ template "contour.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
