apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weave-scope-app
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
        - name: app
          image: "weaveworks/scope:{{ .Values.imageTag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          resources:
            limits:
              cpu: "{{ .Values.cpuApp }}"
              memory: "{{ .Values.memoryApp }}"
            requests:
              cpu: 100m
              memory: 100Mi
          args:
            - '--no-probe'
          ports:
            - containerPort: 4040
              protocol: TCP
